name: build and test template
description: "A template to build and test docker image based on provided inputs"

inputs:
  docker-auth-token:
    description: 'Docker Hub authentication token'
    required: true
  image-name:
    description: 'image name to be built'
    required: true
  dockerfile-name:
    description: 'The name of dockerfile to use'
    required: true
  platform:
    description: 'The platform to build'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set env vars for main branch
      shell: bash
      run: |
        echo "TAG_NAME=latest" >> "$GITHUB_ENV"
      if: startsWith(github.ref, 'refs/heads/main')
    - name: Set env vars for other branch
      shell: bash
      run: |
        echo "TAG_NAME=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
      if: ${{ !startsWith(github.ref, 'refs/heads/main') }}
    - name: Attach platform to tag
      shell: bash
      run: |
        echo "TAG_NAME=${{env.TAG_NAME}}-${{inputs.platform}}" >> "$GITHUB_ENV"
      if: "${{ inputs.platform != 'ARM64' }}"
    - name: Create Cache and Builder for Buildx
      shell: bash
      run: |
          docker buildx create --use --name mybuilder --node mybuilder

    - name: Build and Cache Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./docker
        file: ./docker/${{ inputs.dockerfile-name}}
        build-args: |
          TAG_NAME=${{ env.TAG_NAME}}
        push: true
        tags: |
          awiciroh/${{ inputs.image-name}}:${{ env.TAG_NAME}}
        builder: mybuilder
        no-cache: true
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled