name: build and push template
description: "A template to build and push docker image based on provided inputs"

inputs:
  docker-auth-token:
    description: 'Docker Hub authentication token'
    required: true
  image-name:
    description: 'image name to be built'
    required: true
  dockerfile-name:
    description: 'The name of dockerfile to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set env vars for main branch
      shell: bash
      run: |
        echo "TAG_NAME=latest" >> "$GITHUB_ENV"
      if: startsWith(github.ref, 'refs/heads/main')
    - name: Set env vars for other branch
      shell: bash
      run: |
        echo "TAG_NAME=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
      if: ${{ !startsWith(github.ref, 'refs/heads/main') }}
    
    - name: Login to Docker Hub
      shell: bash
      run: |
          echo "${{ inputs.docker-auth-token }}" | docker login --username awiciroh --password-stdin
    
    - name: Create Cache and Builder for Buildx
      shell: bash
      run: |
          docker buildx create --use --name mybuilder --node mybuilder

    - name: Build and Cache Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/${{ inputs.dockerfile-name}}
        push: true
        platforms: linux/arm64
        tags: |
          awiciroh/${{ inputs.image-name}}:${{ env.TAG_NAME}}
        builder: mybuilder
        no-cache: true
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
